weba:
  image: nginx:${NGINX_VERSION}
  volumes:
    - ${LOCAL_STOARGE_PATH}/docker-${APP_NAME}/web1:/usr/share/nginx/html
  expose:
    - ${HTTP_PORT}

webb:
  image: nginx:${NGINX_VERSION}
  volumes:
    - ${LOCAL_STOARGE_PATH}/docker-${APP_NAME}/web2:/usr/share/nginx/html
  expose:
    - ${HTTP_PORT}

webc:
  image: nginx:${NGINX_VERSION}
  volumes:
    - ${LOCAL_STOARGE_PATH}/docker-${APP_NAME}/web3:/usr/share/nginx/html
  expose:
    - ${HTTP_PORT}

haproxy:
  image: haproxy
  volumes:
    - ${LOCAL_STOARGE_PATH}/docker-${APP_NAME}/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  links:
    - weba
    - webb
    - webc
  ports:
    - "${HTTP_PORT}:80"
    - "8099:70"
  expose:
    - "${HTTP_PORT}"

