weba:
  image: nginx:1.13.0-alpine
  volumes:
    - ./web1:/usr/share/nginx/html
  expose:
    - 80

webb:
  image: nginx:1.13.0-alpine
  volumes:
    - ./web2:/usr/share/nginx/html
  expose:
    - 80

webc:
  image: nginx:1.13.0-alpine
  volumes:
    - ./web3:/usr/share/nginx/html
  expose:
    - 80

haproxy:
  image: haproxy
  volumes:
    - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  links:
    - weba
    - webb
    - webc
  ports:
    - "811:80"
    - "70:70"

