weba:
  image: nginx:${NGINX_VERSION}
  volumes:
    - ${LOCAL_STOARGE_PATH}/www/web1:/usr/share/nginx/html
  environment:
    - TZ=${SERVER_TIMEZONE}
  expose:
    - 80

webb:
  image: nginx:${NGINX_VERSION}
  volumes:
    - ${LOCAL_STOARGE_PATH}/www/web2:/usr/share/nginx/html
  environment:
    - TZ=${SERVER_TIMEZONE}
  expose:
    - 80

webc:
  image: nginx:${NGINX_VERSION}
  volumes:
    - ${LOCAL_STOARGE_PATH}/www/web3:/usr/share/nginx/html
  environment:
    - TZ=${SERVER_TIMEZONE}
  expose:
    - 80

haproxy:
  image: haproxy
  volumes:
    - ${LOCAL_STOARGE_PATH}/docker-${APP_NAME}/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  links:
    - weba
    - webb
    - webc
  ports:
    - "${HTTP_PORT}:80"
    - "70:70"

