version: '3'
services:
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    volumes:
      - ${LOCAL_STOARGE_PATH}/docker-${APP_NAME}/redis/redis.conf/:/usr/local/etc/redis.conf
      - ${LOCAL_STOARGE_PATH}/docker-${APP_NAME}/redis/data:/usr/local/redis/data
      - ${LOCAL_STOARGE_PATH}/log/redis.log:/usr/local/redis/redis.log
    command:
      redis-server
    networks:
      - backend
    restart: always

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ${LOCAL_STOARGE_PATH}/docker-${APP_NAME}/mysql/data:/var/lib/mysql
      - ${LOCAL_STOARGE_PATH}/docker-${APP_NAME}/mysql/my.cnf:/etc/my.cnf
    environment:
      - TZ=${SERVER_TIMEZONE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - backend
    restart: always

  php:
    build: ./dockerfile
    container_name: php
    ports:
      - "${HTTP_PORT}:80"
    networks:
      - frontend
      - backend
    restart: always

networks:
  frontend:
  backend: