version: '3'
services:
  nginx:
    build: ./nginx
    depends_on:
      - php
    ports:
      - "810:80"
      - "443:443"
    volumes:
      - ../www:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    networks:
      - frontend
    restart: always
    container_name: nginx

  php:
    build: ./php
    volumes:
      - ../www:/var/www/html
      - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
    networks:
      - frontend
      - backend
    restart: always
    container_name: php

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - backend
    restart: always
    container_name: mysql

  redis:
    image: redis:3.2-alpine
    container_name: redis
    volumes:
      - ./redis/redis.conf/:/usr/local/etc/redis.conf
      - ./redis/data:/usr/local/redis/data
      - ./redis/redis.log:/usr/local/redis/redis.log
    command:
      redis-server
    networks:
      - backend
    restart: always

networks:
  frontend:
  backend:
